# Generated by Django 6.0.2 on 2026-03-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_at',
        ),
    ]
