# Generated by Django 6.0.2 on 2026-03-16 14:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
