# Generated by Django 6.0.2 on 2026-03-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
