# Generated by Django 6.0.2 on 2026-03-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('service', '0004_service_latitude_service_longitude'),
        ('user_auth', '0002_userauth_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('service', 'customer', 'provider')},
        ),
    ]
