# Generated by Django 6.0.2 on 2026-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_booked',
            field=models.BooleanField(default=True),
        ),
    ]
