# Generated by Django 6.0.2 on 2026-04-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_is_booked'),
        ('service', '0009_remove_service_is_booked'),
        ('user_auth', '0002_userauth_otp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('service', 'seller', 'buyer'), name='unique_chat_room'),
        ),
    ]
