# Generated by Django 6.0.2 on 2026-04-25 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_unique_together_and_more'),
        ('service', '0009_remove_service_is_booked'),
        ('user_auth', '0002_userauth_otp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatroom',
            name='unique_chat_room',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_delivered',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.userauth'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('service', 'seller', 'buyer')},
        ),
    ]
