# Generated by Django 6.0.2 on 2026-04-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatroom_unique_chat_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
