# Generated by Django 6.0.2 on 2026-04-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='is_booked',
        ),
    ]
