# Generated by Django 6.0.2 on 2026-04-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chatroom_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
