# Generated by Django 6.0.2 on 2026-03-17 08:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_service_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
