# Generated by Django 6.0.2 on 2026-04-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_latitude_service_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='swipe_status',
            field=models.BooleanField(default=False),
        ),
    ]
