# Generated by Django 6.0.2 on 2026-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_swipe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_active',
            field=models.BooleanField(default=True),
        ),
    ]
