# Generated by Django 6.0.2 on 2026-04-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_service_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_active',
        ),
    ]
