# Generated by Django 6.0.2 on 2026-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_service_service_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
