# Generated by Django 6.0.2 on 2026-04-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_service_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_booked',
        ),
    ]
